project:
  type: website
  output-dir: docs

website:
  title: "DeLuca BioBlitz"
  navbar:
    left:
      - href: index.qmd
        text: Species

format:
  html:
    theme: cosmo
    toc: false
    toc-depth: 2
    # remove toc-location: left
    css: styles.css

execute:
  freeze: auto
